import com.mongodb.*;
import java.util.Set;
public class Register extends javax.swing.JFrame {
MongoClient mongo;
    /**
     * Creates new form Register
     */
    public Register() {
        getconnect();
        initComponents();
    }
public void getconnect(){
    try{
        mongo = new MongoClient("localhost",27017);
    }catch(Exception e){
        System.out.println(e);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pwd_txt = new javax.swing.JTextField();
        user_txt = new javax.swing.JTextField();
        register_txt = new javax.swing.JButton();
        connect_txt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pwd_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 196, 28));
        getContentPane().add(user_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 50, 196, 28));

        register_txt.setText("Register");
        register_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_txtActionPerformed(evt);
            }
        });
        getContentPane().add(register_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 130, 30));

        connect_txt.setText("Connect to DB");
        connect_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connect_txtActionPerformed(evt);
            }
        });
        getContentPane().add(connect_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 130, 30));

        jButton1.setText("remove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        jButton2.setText("check");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        jButton3.setText("show");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void register_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_txtActionPerformed
       String user = user_txt.getText();
       String pwd = pwd_txt.getText();
       try{
       DB db = mongo.getDB("test");
       DBCollection table = db.getCollection("eiei");
       DBCursor cursor = table.find();
       //Set<String> table = db.getCollectionNames();
       while (cursor.hasNext()) {
	System.out.println(cursor.next());
	}
       BasicDBObject doc = new BasicDBObject();
       doc.put("username", user);
       doc.put("password",pwd);
       table.insert(doc);
       System.out.println("insert successfully");
       }catch(Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_register_txtActionPerformed

    private void connect_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connect_txtActionPerformed
        getconnect();
    }//GEN-LAST:event_connect_txtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
       DB db = mongo.getDB("test");
       DBCollection table = db.getCollection("eiei");
       BasicDBObject doc = new BasicDBObject();
       doc.put("username","adminz");
       table.remove(doc);
       System.out.println("remove successfully");
       }catch(Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
       DB db = mongo.getDB("test");
       DBCollection table = db.getCollection("eiei");
       DBCursor cursor = table.find();
       //Set<String> table = db.getCollectionNames();
       while (cursor.hasNext()) {
	System.out.println(cursor.next());
	}  
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connect_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField pwd_txt;
    private javax.swing.JButton register_txt;
    private javax.swing.JTextField user_txt;
    // End of variables declaration//GEN-END:variables
}
